/**
 * ~/.gemini/policies/illithid.toml — command rules for Gemini CLI's policy engine (the whole file is the app's).
 *
 * Gemini CLI reads every .toml in ~/.gemini/policies (user tier). The highest priority wins, so deny 300 > ask 200 > allow
 * 100 gives the same order as the other tools. commandPrefix is a plain string prefix (`git push --force` would also match
 * `--force-with-lease`), so each rule is a regex that ends at a word boundary: `^git push --force(\s|$)`; exact → `^…$`.
 * Checked 2026-10-01: geminicli.com/docs/reference/policy-engine/
 */
import { geminiMcpRules, type GeminiMcpRule } from '../mcpPermissions'
import { mcpEntries, normalizeEntry } from '../text'
import { allowlistFor } from '../permissions'
import { TargetError, type Allowlist, type TargetDef } from '../types'

export const GEMINI_POLICY_HEADER =
  '# Generated by Illithid from the library permissions.json. Edit the rules in Illithid; this file is rewritten on sync.'

const DECISIONS = [
  { key: 'bashDeny', decision: 'deny', priority: 300 },
  { key: 'bashAsk', decision: 'ask_user', priority: 200 },
  { key: 'bash', decision: 'allow', priority: 100 }
] as const

const escapeRegex = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

export function geminiPolicyText(
  allowlist: Allowlist | null,
  mcpRules: readonly GeminiMcpRule[] = []
): string {
  const out = [GEMINI_POLICY_HEADER, '']
  for (const { key, decision, priority } of DECISIONS)
    for (const e of allowlist?.[key] ?? []) {
      const { argv, claudeExact } = normalizeEntry(e)
      const re = `^${escapeRegex(argv.join(' '))}${claudeExact ? '$' : '(\\s|$)'}`
      out.push(
        '[[rule]]',
        'toolName = "run_shell_command"',
        `commandRegex = ${JSON.stringify(re)}`,
        `decision = "${decision}"`,
        `priority = ${priority}`,
        ''
      )
    }
  // MCP servers' tool rules (mcpPermissions.ts)
  for (const r of mcpRules)
    out.push(
      '[[rule]]',
      `mcpName = ${JSON.stringify(r.mcpName)}`,
      ...(r.toolName ? [`toolName = ${JSON.stringify(r.toolName)}`] : []),
      `decision = "${r.decision}"`,
      `priority = ${r.priority}`,
      ''
    )
  return out.join('\n')
}

const ours = (text: string): boolean => text.startsWith(GEMINI_POLICY_HEADER)

export const geminiPolicy: TargetDef = {
  id: 'geminiPolicy',
  tool: 'gemini',
  rel: '.gemini/policies/illithid.toml',
  optional: true,
  seed: '',
  region: (text) => (ours(text) ? text : null),
  build(before, { sources, retiring }) {
    const mcpRules = retiring
      ? []
      : mcpEntries(sources.mcp).flatMap(([name, s]) => geminiMcpRules(name, s))
    if (!sources.hasPermissions && !mcpRules.length && !before.trim())
      return { after: before, notes: ['no command or MCP tool rules — nothing to write'] }
    if (before.trim() && !ours(before))
      throw new TargetError(
        '.gemini/policies/illithid.toml exists and is not the app’s — not written'
      )
    // Gemini turned off or no permissions.json: the app's file stays, with no rules
    const after = geminiPolicyText(
      retiring || !sources.hasPermissions ? null : allowlistFor(sources.allowlist, 'gemini'),
      mcpRules
    )
    if (!before.trim() && after === geminiPolicyText(null))
      return { after: before, notes: ['no command rules'] }
    return { after, notes: [`${(after.match(/^\[\[rule\]\]$/gm) ?? []).length} rules`] }
  }
}
