/**
 * What each tool runs for a hook.
 * - Built-in actions (notify, guard, format, log) → a /bin/sh script per tool. It reads the tool's own hook input with the macOS
 *   built-in plutil (no jq), blocks with exit 2 and a reason on stderr (every tool honors that before a tool runs) and prints
 *   nothing on stdout (Gemini CLI parses stdout as JSON)
 * - ask → the Claude Code prompt: the user's instruction, the event as $ARGUMENTS and the reply format the event expects
 * - script → the hook's own run.sh (or the tool's run.<tool>.sh)
 */
import type { HookTool } from './hookEvents'
import { scriptForTool, type HookDoc, type LibraryHook } from './hooks'

const q = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`

/** Shell expression for a path that may start with ~/ */
const homePath = (p: string): string => (p.startsWith('~/') ? `"$HOME"/${q(p.slice(2))}` : q(p))

const HEADER = (tool: HookTool, name: string): string[] => [
  '#!/bin/sh',
  `# Generated by Illithid for ${tool} (hook: ${name}). Edit the hook in Illithid; this file is rewritten on sync.`,
  'input=$(cat)',
  `field() { printf '%s' "$input" | /usr/bin/plutil -extract "$1" raw -o - - 2>/dev/null; }`
]

/** Shell lines that set $1 of the function to the value of a tool-call argument (command, file path) */
function argGetter(tool: HookTool): string[] {
  switch (tool) {
    case 'copilot':
      // toolArgs is a JSON string in the CLI (an object in some docs) — try both
      return [
        `arg() { v=$(field toolArgs | /usr/bin/plutil -extract "$1" raw -o - - 2>/dev/null) || v=$(field "toolArgs.$1"); printf '%s' "$v"; }`
      ]
    case 'grok':
      return [`arg() { field "toolInput.$1" || field "tool_input.$1"; }`]
    default:
      return [`arg() { field "tool_input.$1"; }`]
  }
}

/** File path argument name per tool */
const FILE_ARG: Record<HookTool, string> = {
  claude: 'file_path',
  codex: 'file_path',
  gemini: 'file_path',
  copilot: 'path',
  grok: 'file_path'
}

/** Script a built-in action runs in one tool */
export function renderActionScript(tool: HookTool, name: string, doc: HookDoc): string {
  const o = doc.options
  const out = HEADER(tool, name)
  switch (doc.action) {
    case 'notify': {
      const title = String(o.title || 'Illithid')
      const message = String(o.message || doc.description || name)
      out.push(
        `/usr/bin/osascript -e 'on run argv' -e 'display notification (item 2 of argv) with title (item 1 of argv)' -e 'end run' ${q(title)} ${q(message)} >/dev/null 2>&1`
      )
      if (o.sound === true)
        out.push('/usr/bin/afplay /System/Library/Sounds/Glass.aiff >/dev/null 2>&1 &')
      break
    }
    case 'guard': {
      out.push(...argGetter(tool), 'cmd=$(arg command)', 'case "$cmd" in')
      for (const p of o.patterns as string[])
        out.push(`  *${q(p)}*) echo ${q(`Blocked by Illithid (${name}): ${p}`)} >&2; exit 2 ;;`)
      out.push('esac')
      break
    }
    case 'format': {
      out.push(
        ...argGetter(tool),
        `file=$(arg ${FILE_ARG[tool]})`,
        '[ -n "$file" ] || exit 0',
        `${String(o.command)} "$file" >/dev/null 2>&1`
      )
      break
    }
    case 'log': {
      out.push(
        `log=${homePath(String(o.path))}`,
        'mkdir -p "$(dirname "$log")"',
        `printf '%s\\t%s\\t%s\\t%s\\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" ${q(tool)} ${q(name)} "$PWD" >> "$log"`
      )
      break
    }
    default:
      throw new Error(`${doc.action} has no generated script`)
  }
  out.push('exit 0', '')
  return out.join('\n')
}

/** Reply format Claude Code expects from a prompt hook, per timing */
const ASK_REPLY: Record<'before-tool' | 'stop' | 'prompt', string> = {
  'before-tool':
    'Reply with JSON only: {"hookSpecificOutput": {"hookEventName": "PreToolUse", "permissionDecision": "allow" or "deny", "permissionDecisionReason": "<why>"}}',
  stop: 'Reply with JSON only. To make Claude keep working: {"decision": "block", "reason": "<what is left to do>"}. Otherwise reply {}',
  prompt:
    'Reply with JSON only. To stop this prompt: {"decision": "block", "reason": "<why>"}. Otherwise reply {}'
}

/** Claude Code prompt for an ask hook ($ in the instruction is escaped so only $ARGUMENTS is substituted) */
export function renderAskPrompt(doc: HookDoc): string {
  if (doc.options.verbatim === true) return doc.body.trim()
  const instruction = doc.body.trim().replace(/\$/g, '\\$')
  const reply = ASK_REPLY[doc.when as keyof typeof ASK_REPLY] ?? ASK_REPLY.stop
  return `${instruction}\n\nThe event, as JSON: $ARGUMENTS\n\n${reply}`
}

/** File name of a tool's script copy, and its content. null for ask (no script) */
export function toolScript(
  tool: HookTool,
  hook: LibraryHook
): { file: string; content: string } | null {
  const { doc } = hook
  if (doc.action === 'ask') return null
  if (doc.action === 'script') {
    const file = scriptForTool(doc, tool)
    return { file, content: hook.scripts[file] ?? '' }
  }
  return { file: 'run.sh', content: renderActionScript(tool, hook.name, doc) }
}
