/**
 * What each tool runs for a hook.
 * - Built-in actions (notify, guard, format, log) → a /bin/sh script per tool. It reads the tool's own hook input with the macOS
 *   built-in plutil (no jq), blocks with exit 2 and a reason on stderr (every tool honors that before a tool runs) and prints
 *   nothing on stdout (Gemini CLI parses stdout as JSON)
 * - ask → the Claude Code prompt: the user's instruction, the event as $ARGUMENTS and the reply format the event expects
 * - script → the hook's own run.sh (or the tool's run.<tool>.sh)
 */
import { HOOK_TOOLS, type HookTool } from './hookEvents'
import { hookSupport, NOTIFY_URL_ENV, type NotifyChannel } from './hookActions'
import { scriptForTool, type HookDoc, type LibraryHook } from './hooks'

const q = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`

/** Shell expression for a path that may start with ~/ */
const homePath = (p: string): string => (p.startsWith('~/') ? `"$HOME"/${q(p.slice(2))}` : q(p))

/** Every generated script steps aside inside a judging run (an ask hook's nested CLI), so hooks never judge recursively */
const JUDGE_GUARD = '[ -n "${ILLITHID_JUDGE:-}" ] && exit 0'

/** Reads the event (stdin) once; field <path> prints one value of it */
const READ_INPUT = [
  JUDGE_GUARD,
  'input=$(cat)',
  `field() { printf '%s' "$input" | /usr/bin/plutil -extract "$1" raw -o - - 2>/dev/null; }`
]

const HEADER = (tool: HookTool, name: string): string[] => [
  '#!/bin/sh',
  `# Generated by Illithid for ${tool} (hook: ${name}). Edit the hook in Illithid; this file is rewritten on sync.`,
  ...READ_INPUT
]

/** Shell lines that set $1 of the function to the value of a tool-call argument (command, file path) */
function argGetter(tool: HookTool): string[] {
  switch (tool) {
    case 'copilot':
      // toolArgs is a JSON string in the CLI (an object in some docs) — try both
      return [
        `arg() { v=$(field toolArgs | /usr/bin/plutil -extract "$1" raw -o - - 2>/dev/null) || v=$(field "toolArgs.$1"); printf '%s' "$v"; }`
      ]
    case 'grok':
      return [`arg() { field "toolInput.$1" || field "tool_input.$1"; }`]
    default:
      return [`arg() { field "tool_input.$1"; }`]
  }
}

/** File path argument name per tool */
const FILE_ARG: Record<HookTool, string> = {
  claude: 'file_path',
  codex: 'file_path',
  gemini: 'file_path',
  copilot: 'path',
  grok: 'file_path',
  qwen: 'file_path'
}

/**
 * notify: macOS notification (osascript, the texts as arguments), or a phone notification posted with curl to an address read
 * from an environment variable at run time (the address is a secret: never written into the hook or the script). The title
 * gets the project folder name so notifications from several sessions can be told apart. At the notification timing an empty
 * message means the tool's own text (its `message` field)
 */
function notifyLines(doc: HookDoc, name: string): string[] {
  const o = doc.options
  const fallback = String(o.message || doc.description || name)
  const out = [`title=${q(String(o.title || 'Illithid'))}`]
  if (o.project !== false) out.push('title="$title · $(basename "$PWD")"')
  out.push(`msg=${q(fallback)}`)
  if (!o.message && doc.when === 'notification')
    out.push(`m=$(field message); [ -n "$m" ] && msg="$m"`)
  const channel = String(o.channel || 'mac') as NotifyChannel
  if (channel === 'mac') {
    out.push(
      `osascript -e 'on run argv' -e 'display notification (item 2 of argv) with title (item 1 of argv)' -e 'end run' "$title" "$msg" >/dev/null 2>&1`
    )
    if (o.sound === true) out.push('afplay /System/Library/Sounds/Glass.aiff >/dev/null 2>&1 &')
    return out
  }
  const envName = String(o.urlEnv || NOTIFY_URL_ENV[channel])
  out.push(`url="\${${envName}:-}"`, '[ -n "$url" ] || exit 0')
  if (channel === 'ntfy')
    out.push(`curl -fsS -m 10 -H "Title: $title" -d "$msg" "$url" >/dev/null 2>&1`)
  else
    out.push(
      // JSON string escaping: backslash, quote; line breaks become spaces
      `esc() { printf '%s' "$1" | tr '\\n' ' ' | sed 's/\\\\/\\\\\\\\/g; s/"/\\\\"/g'; }`,
      `body=$(printf '{"text":"*%s*\\\\n%s"}' "$(esc "$title")" "$(esc "$msg")")`,
      `curl -fsS -m 10 -H 'Content-Type: application/json' -d "$body" "$url" >/dev/null 2>&1`
    )
  return out
}

/** JSON string escaping in sh: control characters dropped, backslash and quote escaped, line breaks as \\n */
const JESC = `jesc() { printf '%s' "$1" | tr -d '\\001-\\011\\013-\\037' | sed 's/\\\\/\\\\\\\\/g; s/"/\\\\"/g' | awk 'BEGIN{ORS=""} NR>1{print "\\\\n"} {print}'; }`

/**
 * context: what the agent should know when a session starts — the git branch and uncommitted changes, and the hook's note.
 * Claude Code and Codex read plain stdout; Gemini CLI and Qwen Code want hookSpecificOutput.additionalContext, Copilot additionalContext
 */
function contextLines(tool: HookTool, doc: HookDoc): string[] {
  const out = ["text=''"]
  if (doc.options.git !== false)
    out.push(
      '# symbolic-ref also names a branch with no commits yet; a detached HEAD shows its commit',
      'if branch=$(git symbolic-ref --short -q HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null); then',
      '  text="Git branch: $branch"',
      '  st=$(git status --short 2>/dev/null | head -n 20)',
      '  [ -n "$st" ] && text="$text',
      'Uncommitted changes:',
      '$st"',
      'fi'
    )
  const note = doc.body.trim()
  if (note) out.push(`note=${q(note)}`, 'text="${text:+$text', '', '}$note"')
  out.push('[ -n "$text" ] || exit 0')
  if (tool === 'gemini' || tool === 'qwen')
    out.push(
      JESC,
      `printf '{"hookSpecificOutput":{"additionalContext":"%s"}}\\n' "$(jesc "$text")"`
    )
  else if (tool === 'copilot')
    out.push(JESC, `printf '{"additionalContext":"%s"}\\n' "$(jesc "$text")"`)
  else out.push(`printf '%s\\n' "$text"`)
  return out
}

/** Ref folder the checkpoint snapshots go to, and how many are kept */
export const CHECKPOINT_REF = 'refs/illithid/checkpoints'
export const CHECKPOINT_KEEP = 50

/**
 * checkpoint, at the end of a reply:
 * - snapshot (default): the whole work tree, new files included, as a commit under refs/illithid/checkpoints/<UTC time>,
 *   built in a temporary index — files, the index and the branch stay as they are. Skipped when nothing changed since the
 *   last snapshot (or since HEAD). The newest CHECKPOINT_KEEP are kept. Restore: git restore --source <ref> -- .
 * - commit: a WIP commit of everything changed on the current branch
 * Commits need an author: the repository's, else "Illithid"
 */
function checkpointLines(doc: HookDoc): string[] {
  const who =
    'git -c user.name="$(git config user.name || echo Illithid)" -c user.email="$(git config user.email || echo illithid@localhost)"'
  const head = [
    'top=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0',
    'cd "$top" || exit 0',
    'stamp=$(date -u +%Y%m%dT%H%M%SZ)'
  ]
  if (doc.options.mode === 'commit')
    return [
      ...head,
      '[ -n "$(git status --porcelain 2>/dev/null)" ] || exit 0',
      'git add -A >/dev/null 2>&1 || exit 0',
      `${who} commit -q -m "WIP: checkpoint $stamp ($1)" >/dev/null 2>&1`
    ]
  return [
    ...head,
    'idx="${TMPDIR:-/tmp}/illithid-ckpt-$$"',
    'cp "$(git rev-parse --git-path index)" "$idx" 2>/dev/null || rm -f "$idx"',
    'GIT_INDEX_FILE="$idx" git add -A >/dev/null 2>&1 || { rm -f "$idx"; exit 0; }',
    'tree=$(GIT_INDEX_FILE="$idx" git write-tree 2>/dev/null)',
    'rm -f "$idx"',
    '[ -n "$tree" ] || exit 0',
    `last=$(git for-each-ref --sort=-refname --count=1 --format='%(objectname)' ${CHECKPOINT_REF})`,
    'if [ -n "$last" ]; then [ "$(git rev-parse "$last^{tree}")" = "$tree" ] && exit 0',
    'elif git rev-parse -q --verify HEAD >/dev/null; then [ "$(git rev-parse "HEAD^{tree}")" = "$tree" ] && exit 0; fi',
    'parent=$(git rev-parse -q --verify HEAD)',
    `commit=$(${who} commit-tree "$tree" \${parent:+-p "$parent"} -m "Illithid checkpoint $stamp ($1)" 2>/dev/null) || exit 0`,
    `git update-ref "${CHECKPOINT_REF}/$stamp" "$commit"`,
    `git for-each-ref --sort=-refname --format='%(refname)' ${CHECKPOINT_REF} | tail -n +${CHECKPOINT_KEEP + 1} | while read -r r; do git update-ref -d "$r"; done`
  ]
}

/** What a judging CLI is asked to answer, per timing */
const JUDGE_REPLY: Record<'before-tool' | 'stop' | 'prompt', string> = {
  'before-tool':
    'Decide whether the tool call above may run under the rule. Reply with JSON only: {"ok": <true or false>, "reason": "<one sentence>"}. ok false blocks the call.',
  stop: 'Decide whether the agent may finish now under the rule. Reply with JSON only: {"ok": <true or false>, "reason": "<what is left to do>"}. ok false sends the agent back to work with the reason.',
  prompt:
    'Decide whether the prompt above may be sent under the rule. Reply with JSON only: {"ok": <true or false>, "reason": "<one sentence>"}. ok false blocks the prompt.'
}

const JUDGE_SCHEMA =
  '{"type":"object","properties":{"ok":{"type":"boolean"},"reason":{"type":"string"}},"required":["ok","reason"],"additionalProperties":false}'

/** The judging CLI call, run with ILLITHID_JUDGE=1 and, where the CLI allows, with hooks and tools off. Sets $out */
function judgeCall(cli: HookTool): string[] {
  switch (cli) {
    case 'claude':
      return [
        `out=$(ILLITHID_JUDGE=1 claude --model "\${model:-haiku}" --tools "" --output-format json --json-schema "$schema" --settings '{"disableAllHooks":true}' -p "$prompt" 2>/dev/null)`,
        'judge_status=$?'
      ]
    case 'codex':
      return [
        'sf="${TMPDIR:-/tmp}/illithid-judge-$$.json"; of="${TMPDIR:-/tmp}/illithid-judge-$$.out"',
        `printf '%s' "$schema" > "$sf"`,
        'ILLITHID_JUDGE=1 codex exec --ephemeral --skip-git-repo-check --disable hooks --sandbox read-only ${model:+-m "$model"} --output-schema "$sf" -o "$of" "$prompt" >/dev/null 2>&1',
        'judge_status=$?',
        'out=$(cat "$of" 2>/dev/null); rm -f "$sf" "$of"'
      ]
    case 'gemini':
      return [
        'out=$(ILLITHID_JUDGE=1 gemini -p "$prompt" --approval-mode plan -o json ${model:+-m "$model"} 2>/dev/null)',
        'judge_status=$?'
      ]
    case 'copilot':
      return [
        'out=$(ILLITHID_JUDGE=1 copilot -p "$prompt" -s --no-ask-user --output-format json ${model:+--model "$model"} 2>/dev/null)',
        'judge_status=$?'
      ]
    case 'qwen':
      // Text output is the final reply alone (-o json prints every message as an array)
      return [
        'out=$(ILLITHID_JUDGE=1 qwen -p "$prompt" --approval-mode plan ${model:+-m "$model"} 2>/dev/null)',
        'judge_status=$?'
      ]
    case 'grok':
      return [
        'out=$(ILLITHID_JUDGE=1 grok -p "$prompt" --json-schema "$schema" --permission-mode plan ${model:+-m "$model"} 2>/dev/null)',
        'judge_status=$?'
      ]
  }
}

/**
 * ask in a tool without LLM-judged hooks (and the all-tools library script): a CLI judges the event against the instruction.
 * The verdict is a boolean in the CLI's JSON result, never text embedded in a quoted reason or another event.
 * Anything else — no CLI, an error, no verdict — lets the event through. "No" is enforced the tool's way:
 * exit 2 with the reason, or Copilot's block decision at the end of a reply
 */
function askLines(tool: HookTool, doc: HookDoc): string[] {
  const o = doc.options
  const cli = (o.judge && o.judge !== 'same' ? o.judge : tool) as HookTool
  const timing = (doc.when in JUDGE_REPLY ? doc.when : 'stop') as keyof typeof JUDGE_REPLY
  const instruction =
    o.verbatim === true
      ? doc.body.trim().replace(/\$ARGUMENTS/g, '(the event JSON below)')
      : doc.body.trim()
  const out: string[] = []
  if (timing === 'stop')
    out.push(
      'active=$(field stop_hook_active); [ -n "$active" ] || active=$(field stopHookActive)',
      '[ "$active" = "true" ] && exit 0'
    )
  out.push(
    'skip_check() { printf \'Illithid AI check skipped: %s. The event is allowed.\\n\' "$1" >&2; exit 0; }',
    `command -v ${cli} >/dev/null 2>&1 || skip_check ${q(`the ${cli} CLI is not installed`)}`,
    `model=${q(String(o.model || ''))}`,
    `schema=${q(JUDGE_SCHEMA)}`,
    'ev=$(printf \'%s\' "$input" | head -c 20000)',
    `prompt="$(printf '%s\\n\\nThe event, as JSON:\\n%s\\n\\n%s' ${q(instruction)} "$ev" ${q(JUDGE_REPLY[timing])})"`,
    ...judgeCall(cli),
    '[ "$judge_status" = 0 ] || skip_check "the judging CLI failed (exit $judge_status)"',
    'json_field() { printf \'%s\' "$1" | /usr/bin/plutil -extract "$2" "$3" -expect "$4" -o - - 2>/dev/null; }',
    'verdict="$out"',
    ...judgeResult(cli),
    'ok=$(json_field "$verdict" ok raw bool)',
    '[ "$ok" = "true" ] || [ "$ok" = "false" ] || skip_check "the judging CLI returned no valid JSON verdict"',
    '[ "$ok" = "false" ] || exit 0',
    'reason=$(json_field "$verdict" reason raw string)',
    `[ -n "$reason" ] || reason=${q('The AI check said no.')}`
  )
  if (tool === 'copilot' && timing === 'stop')
    out.push(JESC, `printf '{"decision":"block","reason":"%s"}\\n' "$(jesc "$reason")"`, 'exit 0')
  else out.push(`printf '%s\\n' "$reason" >&2`, 'exit 2')
  return out
}

/** Select only the documented result field in a CLI envelope; a direct JSON verdict also works. */
function judgeResult(cli: HookTool): string[] {
  switch (cli) {
    case 'claude':
      return [
        'wrapped=$(json_field "$out" structured_output json dictionary) || wrapped=$(json_field "$out" result raw string)',
        '[ -z "$wrapped" ] || verdict="$wrapped"'
      ]
    case 'gemini':
      return [
        'wrapped=$(json_field "$out" response raw string)',
        '[ -z "$wrapped" ] || verdict="$wrapped"'
      ]
    case 'grok':
      return [
        'wrapped=$(json_field "$out" result json dictionary) || wrapped=$(json_field "$out" result raw string)',
        '[ -z "$wrapped" ] || verdict="$wrapped"'
      ]
    case 'copilot':
      return [
        // Copilot emits JSONL. Only its assistant message is a verdict, not another event's metadata.
        "verdict=''",
        'while IFS= read -r event; do',
        '  [ "$(json_field "$event" type raw string)" = "assistant.message" ] || continue',
        '  verdict=$(json_field "$event" data.content raw string)',
        'done <<ILLITHID_JUDGE_OUTPUT',
        '$out',
        'ILLITHID_JUDGE_OUTPUT'
      ]
    case 'qwen':
      // Plain text reply: keep the outermost {…} so a fenced or prefaced answer still reads as the verdict
      return [
        "wrapped=$(printf '%s' \"$out\" | tr '\\n' ' ' | sed -e 's/^[^{]*//' -e 's/[^}]*$//')",
        '[ -z "$wrapped" ] || verdict="$wrapped"'
      ]
    case 'codex':
      return []
  }
}

/** Times one session may be sent back before the check lets the agent finish */
export const VERIFY_MAX_TRIES = 3

/**
 * verify: before the agent finishes, run the project's tests and send it back with the failure if they fail.
 * - Never twice in a row: the tools flag a stop that comes from a stop hook (stop_hook_active, stopHookActive in Grok/Copilot)
 * - At most VERIFY_MAX_TRIES per session (a counter in $TMPDIR), then the agent may finish
 * - Skipped when there is nothing to test with, or the git work tree has no changes (a question answered, nothing edited)
 * - A missing command (exit 127) or pytest finding no tests (exit 5) lets the agent finish
 * - Copilot reads a JSON decision on stdout; the others take exit 2 with the reason on stderr
 */
function verifyLines(tool: HookTool, name: string, doc: HookDoc): string[] {
  const own = String(doc.options.command || '').trim()
  const reply =
    tool === 'copilot'
      ? [JESC, `printf '{"decision":"block","reason":"%s"}\\n' "$(jesc "$reason")"`, 'exit 0']
      : [`printf '%s\\n' "$reason" >&2`, 'exit 2']
  return [
    'active=$(field stop_hook_active); [ -n "$active" ] || active=$(field stopHookActive)',
    '[ "$active" = "true" ] && exit 0',
    `cmd=${q(own)}`,
    'if [ -z "$cmd" ]; then',
    "  if [ -f package.json ] && grep -q '\"test\"[[:space:]]*:' package.json && ! grep -q 'no test specified' package.json; then cmd='npm test --silent'",
    "  elif [ -f pytest.ini ] || [ -f pyproject.toml ] || [ -f setup.cfg ]; then cmd='pytest -q'",
    "  elif [ -f go.mod ]; then cmd='go test ./...'",
    "  elif [ -f Cargo.toml ]; then cmd='cargo test --quiet'",
    '  fi',
    'fi',
    '[ -n "$cmd" ] || exit 0',
    '# Nothing changed in the work tree: nothing to check',
    'if git rev-parse --is-inside-work-tree >/dev/null 2>&1 && [ -z "$(git status --porcelain 2>/dev/null)" ]; then exit 0; fi',
    'sid=$(field session_id); [ -n "$sid" ] || sid=$(field sessionId); [ -n "$sid" ] || sid=$PPID',
    `count="\${TMPDIR:-/tmp}/illithid-verify-$(printf '%s' ${q(name)}"-$sid" | cksum | cut -d' ' -f1)"`,
    'tries=$(cat "$count" 2>/dev/null || echo 0)',
    `if [ "$tries" -ge ${VERIFY_MAX_TRIES} ]; then rm -f "$count"; exit 0; fi`,
    'log=$(sh -c "$cmd" 2>&1)',
    'code=$?',
    '# 127: the command is not installed; 5: pytest found no tests — nothing to hold the agent back for',
    'if [ $code -eq 0 ] || [ $code -eq 127 ] || [ $code -eq 5 ]; then rm -f "$count"; exit 0; fi',
    'echo $((tries + 1)) > "$count"',
    'reason="The check before finishing failed ($cmd). Fix it before you finish:',
    '$(printf \'%s\\n\' "$log" | tail -n 40)"',
    ...reply
  ]
}

/** Script a built-in action runs in one tool */
export function renderActionScript(tool: HookTool, name: string, doc: HookDoc): string {
  return [...HEADER(tool, name), ...actionBody(tool, name, doc), 'exit 0', ''].join('\n')
}

/**
 * One script for every tool (a library script): each tool's body as a function, picked by the tool name Illithid passes as
 * $1. Tools the recipe can't run in fall through and do nothing
 */
export function renderUniversalScript(name: string, doc: HookDoc): string {
  const tools = HOOK_TOOLS.filter((t) => hookSupport(doc.action, doc.when, t) === 'ok')
  const out = [
    '#!/bin/sh',
    `# ${name}: Illithid's "${doc.action}" recipe for every tool. $1 is the tool that runs it (${HOOK_TOOLS.join(', ')}).`,
    ...READ_INPUT
  ]
  for (const t of tools) out.push(`for_${t}() {`, ...actionBody(t, name, doc), 'exit 0', '}')
  out.push('case "$1" in', ...tools.map((t) => `  ${t}) for_${t} "$@" ;;`), 'esac', 'exit 0', '')
  return out.join('\n')
}

/** The lines a built-in action runs in one tool, after the input is read */
function actionBody(tool: HookTool, name: string, doc: HookDoc): string[] {
  const o = doc.options
  const out: string[] = []
  switch (doc.action) {
    case 'notify':
      out.push(...notifyLines(doc, name))
      break
    case 'verify':
      out.push(...verifyLines(tool, name, doc))
      break
    case 'guard': {
      out.push(...argGetter(tool), 'cmd=$(arg command)', 'case "$cmd" in')
      for (const p of o.patterns as string[])
        out.push(`  *${q(p)}*) echo ${q(`Blocked by Illithid (${name}): ${p}`)} >&2; exit 2 ;;`)
      out.push('esac')
      break
    }
    case 'format': {
      if (doc.when === 'stop')
        // Once per reply, on every changed or new file of the git work tree (names with spaces kept whole)
        out.push(
          'git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0',
          '{ git diff --name-only --diff-filter=ACMR HEAD 2>/dev/null; git ls-files --others --exclude-standard; } | sort -u > "${TMPDIR:-/tmp}/illithid-fmt-$$"',
          '[ -s "${TMPDIR:-/tmp}/illithid-fmt-$$" ] || { rm -f "${TMPDIR:-/tmp}/illithid-fmt-$$"; exit 0; }',
          `tr '\\n' '\\0' < "\${TMPDIR:-/tmp}/illithid-fmt-$$" | xargs -0 ${String(o.command)} >/dev/null 2>&1`,
          'rm -f "${TMPDIR:-/tmp}/illithid-fmt-$$"'
        )
      else
        out.push(
          ...argGetter(tool),
          `file=$(arg ${FILE_ARG[tool]})`,
          '[ -n "$file" ] || exit 0',
          `${String(o.command)} "$file" >/dev/null 2>&1`
        )
      break
    }
    case 'protect': {
      out.push(
        ...argGetter(tool),
        `file=$(arg ${FILE_ARG[tool]})`,
        '[ -n "$file" ] || exit 0',
        'base=$(basename "$file")'
      )
      // Patterns are plain globs (PROTECT_PATTERN_RE): unquoted so * and ? match
      for (const p of o.patterns as string[]) {
        const why = `echo ${q(`Protected by Illithid (${name}): `)}"$file"${q(` matches ${p}`)} >&2; exit 2`
        out.push(
          p.includes('/')
            ? `case "$file" in */${p} | ${p}) ${why} ;; esac`
            : `case "$base" in ${p}) ${why} ;; esac`
        )
      }
      break
    }
    case 'context':
      out.push(...contextLines(tool, doc))
      break
    case 'ask':
      out.push(...askLines(tool, doc))
      break
    case 'checkpoint':
      out.push(...checkpointLines(doc))
      break
    case 'log': {
      out.push(
        `log=${homePath(String(o.path))}`,
        'mkdir -p "$(dirname "$log")"',
        `printf '%s\\t%s\\t%s\\t%s\\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" ${q(tool)} ${q(name)} "$PWD" >> "$log"`
      )
      break
    }
    default:
      throw new Error(`${doc.action} has no generated script`)
  }
  return out
}

/**
 * Check script for permission deny rules in a tool that can't keep them (Copilot CLI): blocks a shell command that is a
 * rule's command, starts with it, or runs it after `&&`, `||`, `;` or `|`. An exact rule blocks only the whole command
 */
export function renderPermissionGuard(
  tool: HookTool,
  rules: readonly { argv: string[]; exact: boolean }[]
): string {
  const out = [
    '#!/bin/sh',
    `# Generated by Illithid for ${tool} from the library permissions.json (deny rules). Rewritten on sync.`,
    'input=$(cat)',
    `field() { printf '%s' "$input" | /usr/bin/plutil -extract "$1" raw -o - - 2>/dev/null; }`,
    ...argGetter(tool),
    'cmd=$(arg command)',
    'case "$cmd" in'
  ]
  for (const r of rules) {
    const c = r.argv.join(' ')
    const pats = r.exact
      ? [q(c)]
      : [
          q(c),
          `${q(`${c} `)}*`,
          ...['&& ', '|| ', '; ', '| ', '&&', ';'].flatMap((sep) => [
            `*${q(`${sep}${c}`)}`,
            `*${q(`${sep}${c} `)}*`
          ])
        ]
    out.push(
      `  ${pats.join('|')}) echo ${q(`Blocked by Illithid permissions: ${c}`)} >&2; exit 2 ;;`
    )
  }
  out.push('esac', 'exit 0', '')
  return out.join('\n')
}

/** Claude Code prompt for an ask hook ($ in the instruction is escaped so only $ARGUMENTS is substituted) */
export function renderAskPrompt(doc: HookDoc): string {
  if (doc.options.verbatim === true) return doc.body.trim()
  const instruction = doc.body.trim().replace(/\$/g, '\\$')
  // Prompt hooks use { ok, reason } for every supported event, unlike command-hook responses.
  const reply = JUDGE_REPLY[doc.when as keyof typeof JUDGE_REPLY] ?? JUDGE_REPLY.stop
  return `${instruction}\n\nThe event, as JSON: $ARGUMENTS\n\n${reply}`
}

/** File name of a tool's script copy, and its content. null for ask (no script) */
export function toolScript(
  tool: HookTool,
  hook: LibraryHook
): { file: string; content: string; folder?: string } | null {
  const { doc } = hook
  // Claude Code judges with its own prompt hook; the other tools run the judging script
  if (doc.action === 'ask' && tool === 'claude') return null
  // A folder library script: the entry of its shared copy (a tool-only script of the hook still wins)
  if (doc.action === 'script' && hook.folder && !doc.toolScripts?.[tool])
    return {
      file: hook.folder.entry,
      content: hook.scripts['run.sh'] ?? '',
      folder: hook.folder.name
    }
  if (doc.action === 'script') {
    const file = scriptForTool(doc, tool)
    return { file, content: hook.scripts[file] ?? '' }
  }
  return { file: 'run.sh', content: renderActionScript(tool, hook.name, doc) }
}
