/**
 * Regenerates src/engine/market/mcpPopular.generated.ts: the most-downloaded npm MCP servers that have an installable
 * official registry entry. Network (GET only), takes several minutes because registry searches are slow. Run before a release:
 *   npx tsx scripts/gen-mcp-popular.ts
 */
import { writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { collectPopularServers, type FetchFn } from '../src/engine/market'

const fetchFn: FetchFn = (url, init) => fetch(url, init)
const OUT = join(resolve(__dirname, '..'), 'src/engine/market/mcpPopular.generated.ts')

async function main(): Promise<void> {
  const items = await collectPopularServers(fetchFn, {
    onProgress: (d, t) => d % 20 === 0 && console.log(`${d}/${t}`)
  })
  if (items.length < 10) throw new Error(`only ${items.length} servers matched — registry may be down, keeping the old list`)
  const body = [
    '// Generated by scripts/gen-mcp-popular.ts — do not edit by hand',
    "import type { MarketMcpItem } from './mcpRegistry'",
    '',
    `export const MCP_POPULAR_AT = '${new Date().toISOString().slice(0, 10)}'`,
    `export const MCP_POPULAR: readonly MarketMcpItem[] = ${JSON.stringify(items, null, 2)}`,
    ''
  ].join('\n')
  writeFileSync(OUT, body)
  console.log(`${items.length} servers → ${OUT}`)
  for (const i of items.slice(0, 15)) console.log(`${i.downloads}\t${i.name}\t${i.npm}`)
}

main().catch((e) => {
  console.error(e)
  process.exitCode = 1
})
