import assert from 'node:assert/strict'
import { test } from 'node:test'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { parse as parseToml } from 'smol-toml'
import {
  createHook,
  createHookToolScript,
  deleteHook,
  pendingSyncCount,
  readHook,
  saveHookDoc,
  setToggle,
  syncAll
} from '../src/engine'
import { applyPreview } from '../src/main/preview'
import { baseEnv, buildDemoHome } from './readme-shots'

function demoHome(tools: string[] = ['claude', 'codex', 'gemini', 'copilot']): string {
  const home = mkdtempSync(join(tmpdir(), 'illithid-hooks-sync-'))
  buildDemoHome(home, { tools: 'all' })
  const cfg = join(home, '.config/illithid/config.json')
  writeFileSync(
    cfg,
    JSON.stringify({ ...JSON.parse(readFileSync(cfg, 'utf8')), toolsInUse: tools })
  )
  return home
}

const sync = (home: string, approvedOnce = false): void => {
  const r = syncAll(home, baseEnv(home), { allowReal: true, approvedOnce })
  assert.equal(r.refused, undefined)
  assert.deepEqual(r.plan.errors, [])
}

const json = (p: string): Record<string, unknown> => JSON.parse(readFileSync(p, 'utf8'))
const copyPath = (home: string, tool: string, hook: string, file = 'run.sh'): string =>
  join(home, `.${tool}/hooks/illithid/${hook}/${file}`)
const command = (home: string, tool: string, hook: string, file = 'run.sh'): string =>
  `'${copyPath(home, tool, hook, file)}' ${tool}`

test('REQ-HOOKS-SYNC-1 a guard hook reaches Claude Code next to the user hooks, as a generated executable script', () => {
  const home = demoHome()
  const settings = join(home, '.claude/settings.json')
  mkdirSync(join(home, '.claude'), { recursive: true })
  const userHook = { matcher: 'Write', hooks: [{ type: 'command', command: '~/bin/mine.sh' }] }
  writeFileSync(
    settings,
    JSON.stringify({ theme: 'dark', hooks: { PreToolUse: [userHook] } }, null, 2)
  )
  createHook(home, 'guard', { description: '', when: 'before-tool', action: 'guard', options: {} })
  sync(home)
  const s = json(settings) as { theme: string; hooks: { PreToolUse: unknown[] } }
  assert.equal(s.theme, 'dark')
  assert.deepEqual(s.hooks.PreToolUse, [
    userHook,
    { matcher: 'Bash', hooks: [{ type: 'command', command: command(home, 'claude', 'guard') }] }
  ])
  const copy = copyPath(home, 'claude', 'guard')
  assert.match(readFileSync(copy, 'utf8'), /^#!\/bin\/sh\n# Generated by Illithid for claude/)
  assert.equal(statSync(copy).mode & 0o777, 0o755)
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
})

test('REQ-HOOKS-SYNC-2 each tool gets its own format: Gemini ms and a name, Copilot a flat list, Codex a TOML block', () => {
  const home = demoHome()
  const codexToml = join(home, '.codex/config.toml')
  mkdirSync(join(home, '.codex'), { recursive: true })
  writeFileSync(codexToml, 'model = "gpt-5"\n')
  createHook(home, 'done', { description: '', when: 'stop', action: 'notify', options: {} })
  const doc = readHook(home, 'done').doc
  saveHookDoc(home, 'done', {
    ...doc,
    tools: { codex: { timeout: 30 }, gemini: { timeout: 30 }, copilot: { timeout: 30 } }
  })
  sync(home)
  const gemini = json(join(home, '.gemini/settings.json')) as { hooks: Record<string, unknown> }
  assert.deepEqual(gemini.hooks.AfterAgent, [
    {
      hooks: [
        {
          name: 'illithid-done',
          type: 'command',
          command: command(home, 'gemini', 'done'),
          timeout: 30000
        }
      ]
    }
  ])
  assert.deepEqual(json(join(home, '.copilot/hooks/illithid.json')), {
    version: 1,
    hooks: {
      agentStop: [{ type: 'command', bash: command(home, 'copilot', 'done'), timeoutSec: 30 }]
    }
  })
  // smol-toml returns null-prototype objects; compare plain values
  const toml = JSON.parse(JSON.stringify(parseToml(readFileSync(codexToml, 'utf8')))) as Record<
    string,
    unknown
  >
  assert.equal(toml.model, 'gpt-5')
  assert.deepEqual(toml.hooks, {
    Stop: [{ hooks: [{ type: 'command', command: command(home, 'codex', 'done'), timeout: 30 }] }]
  })
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
})

test('REQ-HOOKS-SYNC-3 a natural-language check becomes a Claude Code prompt hook and reaches no other tool', () => {
  const home = demoHome(['claude', 'gemini'])
  const settings = join(home, '.claude/settings.json')
  mkdirSync(join(home, '.claude'), { recursive: true })
  const userPrompt = { hooks: [{ type: 'prompt', prompt: 'my own check $ARGUMENTS' }] }
  writeFileSync(settings, JSON.stringify({ hooks: { Stop: [userPrompt] } }))
  createHook(home, 'tests', {
    description: '',
    when: 'stop',
    action: 'ask',
    options: {},
    body: 'Keep working until the tests pass.'
  })
  sync(home)
  const stop = (json(settings) as { hooks: { Stop: { hooks: Record<string, unknown>[] }[] } }).hooks
    .Stop
  assert.equal(stop.length, 2)
  assert.deepEqual(stop[0], userPrompt)
  const mine = stop[1].hooks[0]
  assert.equal(mine.type, 'prompt')
  assert.equal(mine.statusMessage, 'Illithid · tests')
  assert.match(String(mine.prompt), /^Keep working until the tests pass\.\n[\s\S]*\$ARGUMENTS/)
  assert.equal(existsSync(copyPath(home, 'claude', 'tests')), false)
  assert.equal((json(join(home, '.gemini/settings.json')) as { hooks?: unknown }).hooks, undefined)
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
  // Turning it off removes only the app entry
  setToggle(home, 'hooks', 'tests', 'claude', false)
  sync(home)
  assert.deepEqual((json(settings) as { hooks: unknown }).hooks, { Stop: [userPrompt] })
})

test('REQ-HOOKS-SYNC-4 turning a tool off or deleting the hook removes only the app entry and backs up the script copy', () => {
  const home = demoHome()
  const settings = join(home, '.claude/settings.json')
  mkdirSync(join(home, '.claude'), { recursive: true })
  const userHook = { hooks: [{ type: 'command', command: 'say done' }] }
  writeFileSync(settings, JSON.stringify({ hooks: { Stop: [userHook] } }, null, 2))
  createHook(home, 'notify', { description: '', when: 'stop', action: 'notify', options: {} })
  sync(home)
  assert.equal((json(settings) as { hooks: { Stop: unknown[] } }).hooks.Stop.length, 2)
  setToggle(home, 'hooks', 'notify', 'claude', false)
  assert.ok(pendingSyncCount(home, baseEnv(home)) > 0)
  sync(home)
  assert.deepEqual((json(settings) as { hooks: unknown }).hooks, { Stop: [userHook] })
  assert.equal(existsSync(copyPath(home, 'claude', 'notify')), false)
  assert.ok(existsSync(join(home, '.config/illithid/backups/deleted')))
  deleteHook(home, 'notify')
  sync(home)
  assert.equal((json(join(home, '.gemini/settings.json')) as { hooks?: unknown }).hooks, undefined)
  assert.equal(existsSync(copyPath(home, 'gemini', 'notify')), false)
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
})

test('REQ-HOOKS-SYNC-5 Grok runs Claude Code hooks by default, so it gets its own entry only when it stops reading them', () => {
  const home = demoHome(['claude', 'grok'])
  createHook(home, 'notify', { description: '', when: 'stop', action: 'notify', options: {} })
  sync(home)
  assert.ok(existsSync(copyPath(home, 'claude', 'notify')))
  assert.equal(existsSync(join(home, '.grok/hooks/illithid.json')), false)
  const cfg = join(home, '.config/illithid/config.json')
  writeFileSync(cfg, JSON.stringify({ ...json(cfg), grokReadsClaude: false }))
  sync(home)
  const grok = json(join(home, '.grok/hooks/illithid.json')) as { hooks: { Stop: unknown[] } }
  assert.deepEqual(grok.hooks.Stop, [
    { hooks: [{ type: 'command', command: command(home, 'grok', 'notify') }] }
  ])
  const compat = parseToml(readFileSync(join(home, '.grok/config.toml'), 'utf8')) as {
    compat: { claude: Record<string, boolean> }
  }
  assert.equal(compat.compat.claude.hooks, false)
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
})

test('REQ-HOOKS-SYNC-6 a script hook copies its own script, a tool-only script only to that tool', () => {
  const home = demoHome()
  createHook(home, 'mine', {
    description: '',
    when: 'session-start',
    action: 'script',
    options: {},
    script: 'shared\n'
  })
  createHookToolScript(home, 'mine', 'copilot')
  sync(home)
  const flat = json(join(home, '.copilot/hooks/illithid.json')) as {
    hooks: { sessionStart: { bash: string }[] }
  }
  assert.equal(flat.hooks.sessionStart[0].bash, command(home, 'copilot', 'mine', 'run.copilot.sh'))
  assert.equal(readFileSync(copyPath(home, 'claude', 'mine'), 'utf8'), 'shared\n')
  assert.equal(existsSync(copyPath(home, 'copilot', 'mine')), false)
})

test('REQ-HOOKS-SYNC-7 the apply preview lists hook entries and script copies; an approved apply restores a copy edited in a tool', () => {
  const home = demoHome()
  createHook(home, 'guard', { description: '', when: 'before-tool', action: 'guard', options: {} })
  let view = applyPreview(home, baseEnv(home))
  const rows = (tool: string): string[] =>
    view.items.filter((x) => x.tool === tool).map((x) => `${x.kind}:${x.action}:${x.name}`)
  assert.ok(rows('claude').includes('hook:add:guard'), rows('claude').join(' '))
  assert.ok(rows('claude').includes('hookScript:add:guard/run.sh'), rows('claude').join(' '))
  assert.ok(view.items.some((x) => x.tool === 'codex' && x.kind === 'hook' && x.codexTrust))
  sync(home)
  const copy = copyPath(home, 'claude', 'guard')
  const generated = readFileSync(copy, 'utf8')
  writeFileSync(copy, 'edited in the tool\n')
  view = applyPreview(home, baseEnv(home))
  assert.ok(rows('claude').includes('hookScript:update:guard/run.sh'), rows('claude').join(' '))
  // Automatic syncs leave the edited copy for the preview; an approved apply restores the generated one
  sync(home)
  assert.equal(readFileSync(copy, 'utf8'), 'edited in the tool\n')
  sync(home, true)
  assert.equal(readFileSync(copy, 'utf8'), generated)
  assert.equal(
    readFileSync(join(home, '.config/illithid/backups/hooks/claude/guard/run.sh'), 'utf8'),
    'edited in the tool\n'
  )
})
