import assert from 'node:assert/strict'
import { test } from 'node:test'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { parse as parseToml } from 'smol-toml'
import { spawnSync } from 'node:child_process'
import {
  createFolderScript,
  createHook,
  createHookToolScript,
  deleteHook,
  keepHookCopy,
  pendingSyncCount,
  readHook,
  saveHookDoc,
  setToggle,
  syncAll,
  writeScriptFile
} from '../src/engine'
import { hooks as hooksView } from '../src/main/reads'
import { applyPreview } from '../src/main/preview'
import { baseEnv, buildDemoHome } from './readme-shots'

function demoHome(tools: string[] = ['claude', 'codex', 'gemini', 'copilot']): string {
  const home = mkdtempSync(join(tmpdir(), 'illithid-hooks-sync-'))
  buildDemoHome(home, { tools: 'all' })
  const cfg = join(home, '.config/illithid/config.json')
  writeFileSync(
    cfg,
    JSON.stringify({ ...JSON.parse(readFileSync(cfg, 'utf8')), toolsInUse: tools })
  )
  return home
}

const sync = (home: string, approvedOnce = false): void => {
  const r = syncAll(home, baseEnv(home), { allowReal: true, approvedOnce })
  assert.equal(r.refused, undefined)
  assert.deepEqual(r.plan.errors, [])
}

const json = (p: string): Record<string, unknown> => JSON.parse(readFileSync(p, 'utf8'))
const copyPath = (home: string, tool: string, hook: string, file = 'run.sh'): string =>
  join(home, `.${tool}/hooks/illithid/${hook}/${file}`)
const command = (home: string, tool: string, hook: string, file = 'run.sh'): string =>
  `'${copyPath(home, tool, hook, file)}' ${tool}`

test('REQ-HOOKS-SYNC-1 a guard hook reaches Claude Code next to the user hooks, as a generated executable script', () => {
  const home = demoHome()
  const settings = join(home, '.claude/settings.json')
  mkdirSync(join(home, '.claude'), { recursive: true })
  const userHook = { matcher: 'Write', hooks: [{ type: 'command', command: '~/bin/mine.sh' }] }
  writeFileSync(
    settings,
    JSON.stringify({ theme: 'dark', hooks: { PreToolUse: [userHook] } }, null, 2)
  )
  createHook(home, 'guard', { description: '', when: 'before-tool', action: 'guard', options: {} })
  sync(home)
  const s = json(settings) as { theme: string; hooks: { PreToolUse: unknown[] } }
  assert.equal(s.theme, 'dark')
  assert.deepEqual(s.hooks.PreToolUse, [
    userHook,
    { matcher: 'Bash', hooks: [{ type: 'command', command: command(home, 'claude', 'guard') }] }
  ])
  const copy = copyPath(home, 'claude', 'guard')
  assert.match(readFileSync(copy, 'utf8'), /^#!\/bin\/sh\n# Generated by Illithid for claude/)
  assert.equal(statSync(copy).mode & 0o777, 0o755)
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
})

test('REQ-HOOKS-SYNC-2 each tool gets its own format: Gemini ms and a name, Copilot a flat list, Codex a TOML block', () => {
  const home = demoHome()
  const codexToml = join(home, '.codex/config.toml')
  mkdirSync(join(home, '.codex'), { recursive: true })
  writeFileSync(codexToml, 'model = "gpt-5"\n')
  createHook(home, 'done', { description: '', when: 'stop', action: 'notify', options: {} })
  const doc = readHook(home, 'done').doc
  saveHookDoc(home, 'done', {
    ...doc,
    tools: { codex: { timeout: 30 }, gemini: { timeout: 30 }, copilot: { timeout: 30 } }
  })
  sync(home)
  const gemini = json(join(home, '.gemini/settings.json')) as { hooks: Record<string, unknown> }
  assert.deepEqual(gemini.hooks.AfterAgent, [
    {
      hooks: [
        {
          name: 'illithid-done',
          type: 'command',
          command: command(home, 'gemini', 'done'),
          timeout: 30000
        }
      ]
    }
  ])
  assert.deepEqual(json(join(home, '.copilot/hooks/illithid.json')), {
    version: 1,
    hooks: {
      agentStop: [{ type: 'command', bash: command(home, 'copilot', 'done'), timeoutSec: 30 }]
    }
  })
  // smol-toml returns null-prototype objects; compare plain values
  const toml = JSON.parse(JSON.stringify(parseToml(readFileSync(codexToml, 'utf8')))) as Record<
    string,
    unknown
  >
  assert.equal(toml.model, 'gpt-5')
  assert.deepEqual(toml.hooks, {
    Stop: [{ hooks: [{ type: 'command', command: command(home, 'codex', 'done'), timeout: 30 }] }]
  })
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
})

test('REQ-HOOKS-SYNC-3 an AI check is a prompt hook in Claude Code and a judging script in the other tools', () => {
  const home = demoHome(['claude', 'gemini'])
  const settings = join(home, '.claude/settings.json')
  mkdirSync(join(home, '.claude'), { recursive: true })
  const userPrompt = { hooks: [{ type: 'prompt', prompt: 'my own check $ARGUMENTS' }] }
  writeFileSync(settings, JSON.stringify({ hooks: { Stop: [userPrompt] } }))
  createHook(home, 'tests', {
    description: '',
    when: 'stop',
    action: 'ask',
    options: {},
    body: 'Keep working until the tests pass.'
  })
  sync(home)
  const stop = (json(settings) as { hooks: { Stop: { hooks: Record<string, unknown>[] }[] } }).hooks
    .Stop
  assert.equal(stop.length, 2)
  assert.deepEqual(stop[0], userPrompt)
  const mine = stop[1].hooks[0]
  assert.equal(mine.type, 'prompt')
  assert.equal(mine.statusMessage, 'Illithid · tests')
  assert.match(String(mine.prompt), /^Keep working until the tests pass\.\n[\s\S]*\$ARGUMENTS/)
  assert.equal(existsSync(copyPath(home, 'claude', 'tests')), false)
  const gemini = json(join(home, '.gemini/settings.json')) as {
    hooks: { AfterAgent: { hooks: { command: string; timeout: number }[] }[] }
  }
  assert.equal(gemini.hooks.AfterAgent[0].hooks[0].command, command(home, 'gemini', 'tests'))
  assert.equal(gemini.hooks.AfterAgent[0].hooks[0].timeout, 120000)
  assert.match(
    readFileSync(copyPath(home, 'gemini', 'tests'), 'utf8'),
    /ILLITHID_JUDGE=1 gemini -p/
  )
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
  // Turning it off removes only the app entry
  setToggle(home, 'hooks', 'tests', 'claude', false)
  sync(home)
  assert.deepEqual((json(settings) as { hooks: unknown }).hooks, { Stop: [userPrompt] })
})

test('REQ-HOOKS-SYNC-4 turning a tool off or deleting the hook removes only the app entry and backs up the script copy', () => {
  const home = demoHome()
  const settings = join(home, '.claude/settings.json')
  mkdirSync(join(home, '.claude'), { recursive: true })
  const userHook = { hooks: [{ type: 'command', command: 'say done' }] }
  writeFileSync(settings, JSON.stringify({ hooks: { Stop: [userHook] } }, null, 2))
  createHook(home, 'notify', { description: '', when: 'stop', action: 'notify', options: {} })
  sync(home)
  assert.equal((json(settings) as { hooks: { Stop: unknown[] } }).hooks.Stop.length, 2)
  setToggle(home, 'hooks', 'notify', 'claude', false)
  assert.ok(pendingSyncCount(home, baseEnv(home)) > 0)
  sync(home)
  assert.deepEqual((json(settings) as { hooks: unknown }).hooks, { Stop: [userHook] })
  assert.equal(existsSync(copyPath(home, 'claude', 'notify')), false)
  assert.ok(existsSync(join(home, '.config/illithid/backups/deleted')))
  deleteHook(home, 'notify')
  sync(home)
  assert.equal((json(join(home, '.gemini/settings.json')) as { hooks?: unknown }).hooks, undefined)
  assert.equal(existsSync(copyPath(home, 'gemini', 'notify')), false)
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
})

test('REQ-HOOKS-SYNC-5 Grok runs Claude Code hooks by default, so it gets its own entry only when it stops reading them', () => {
  const home = demoHome(['claude', 'grok'])
  createHook(home, 'notify', { description: '', when: 'stop', action: 'notify', options: {} })
  sync(home)
  assert.ok(existsSync(copyPath(home, 'claude', 'notify')))
  assert.equal(existsSync(join(home, '.grok/hooks/illithid.json')), false)
  const cfg = join(home, '.config/illithid/config.json')
  writeFileSync(cfg, JSON.stringify({ ...json(cfg), grokReadsClaude: false }))
  sync(home)
  const grok = json(join(home, '.grok/hooks/illithid.json')) as { hooks: { Stop: unknown[] } }
  assert.deepEqual(grok.hooks.Stop, [
    { hooks: [{ type: 'command', command: command(home, 'grok', 'notify') }] }
  ])
  const compat = parseToml(readFileSync(join(home, '.grok/config.toml'), 'utf8')) as {
    compat: { claude: Record<string, boolean> }
  }
  assert.equal(compat.compat.claude.hooks, false)
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
})

test('REQ-HOOKS-SYNC-6 a script hook copies its own script, a tool-only script only to that tool', () => {
  const home = demoHome()
  createHook(home, 'mine', {
    description: '',
    when: 'session-start',
    action: 'script',
    options: {},
    script: 'shared\n'
  })
  createHookToolScript(home, 'mine', 'copilot')
  sync(home)
  const flat = json(join(home, '.copilot/hooks/illithid.json')) as {
    hooks: { sessionStart: { bash: string }[] }
  }
  assert.equal(flat.hooks.sessionStart[0].bash, command(home, 'copilot', 'mine', 'run.copilot.sh'))
  assert.equal(readFileSync(copyPath(home, 'claude', 'mine'), 'utf8'), 'shared\n')
  assert.equal(existsSync(copyPath(home, 'copilot', 'mine')), false)
})

test('REQ-HOOKS-SYNC-7 the apply preview lists hook entries and script copies; an approved apply restores a copy edited in a tool', () => {
  const home = demoHome()
  createHook(home, 'guard', { description: '', when: 'before-tool', action: 'guard', options: {} })
  let view = applyPreview(home, baseEnv(home))
  const rows = (tool: string): string[] =>
    view.items.filter((x) => x.tool === tool).map((x) => `${x.kind}:${x.action}:${x.name}`)
  assert.ok(rows('claude').includes('hook:add:guard'), rows('claude').join(' '))
  assert.ok(rows('claude').includes('hookScript:add:guard/run.sh'), rows('claude').join(' '))
  assert.ok(view.items.some((x) => x.tool === 'codex' && x.kind === 'hook' && x.codexTrust))
  sync(home)
  const copy = copyPath(home, 'claude', 'guard')
  const generated = readFileSync(copy, 'utf8')
  writeFileSync(copy, 'edited in the tool\n')
  view = applyPreview(home, baseEnv(home))
  assert.ok(rows('claude').includes('hookScript:update:guard/run.sh'), rows('claude').join(' '))
  // Automatic syncs leave the edited copy for the preview; an approved apply restores the generated one
  sync(home)
  assert.equal(readFileSync(copy, 'utf8'), 'edited in the tool\n')
  sync(home, true)
  assert.equal(readFileSync(copy, 'utf8'), generated)
  assert.equal(
    readFileSync(join(home, '.config/illithid/backups/hooks/claude/guard/run.sh'), 'utf8'),
    'edited in the tool\n'
  )
})

const FOLDER_RUN = '#!/bin/sh\n. "$(dirname "$0")/lib/util.sh"\nsay_done "$1" "$2"\n'
const UTIL = 'say_done() { echo "done $1 $2"; }\n'
const folderCopy = (home: string, tool: string, name = 'fmt'): string =>
  join(home, `.${tool}/hooks/illithid/_scripts/${name}`)

/** A folder script "fmt" (run.sh calls lib/util.sh) used by hooks a (stop) and b (session start) */
function folderScriptHome(): string {
  const home = demoHome(['claude', 'gemini'])
  createFolderScript(home, 'fmt', { content: FOLDER_RUN })
  writeScriptFile(home, 'fmt', 'lib/util.sh', UTIL)
  createHook(home, 'a', {
    description: '',
    when: 'stop',
    action: 'script',
    options: { use: 'fmt' }
  })
  createHook(home, 'b', {
    description: '',
    when: 'session-start',
    action: 'script',
    options: { use: 'fmt' }
  })
  return home
}

test('REQ-HOOKS-SYNC-8 a folder script reaches each tool once, whole; the hooks using it run its entry, which finds its files', () => {
  const home = folderScriptHome()
  const rows = applyPreview(home, baseEnv(home))
    .items.filter((x) => x.tool === 'claude' && x.kind === 'hookScript')
    .map((x) => `${x.action}:${x.name}`)
  assert.deepEqual(rows, ['add:_scripts/fmt'])
  sync(home)
  for (const tool of ['claude', 'gemini']) {
    const dir = folderCopy(home, tool)
    assert.equal(readFileSync(join(dir, 'run.sh'), 'utf8'), FOLDER_RUN)
    assert.equal(readFileSync(join(dir, 'lib/util.sh'), 'utf8'), UTIL)
    assert.ok(existsSync(join(dir, 'SCRIPT.md')))
    assert.equal(statSync(join(dir, 'run.sh')).mode & 0o111, 0o111)
    // No copy per hook
    assert.equal(existsSync(join(home, `.${tool}/hooks/illithid/a`)), false)
  }
  const claude = json(join(home, '.claude/settings.json')) as {
    hooks: Record<string, { hooks: { command: string }[] }[]>
  }
  const cmd = claude.hooks.Stop[0].hooks[0].command
  assert.equal(cmd, `'${join(folderCopy(home, 'claude'), 'run.sh')}' claude a`)
  assert.equal(
    claude.hooks.SessionStart[0].hooks[0].command,
    `'${join(folderCopy(home, 'claude'), 'run.sh')}' claude b`
  )
  // The entry runs in place and finds lib/util.sh next to it
  const r = spawnSync('/bin/sh', ['-c', cmd], { encoding: 'utf8', cwd: tmpdir() })
  assert.equal(r.stdout, 'done claude a\n')
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
  // Editing a file of the script reaches the copies
  writeScriptFile(home, 'fmt', 'lib/util.sh', 'say_done() { echo "v2 $1"; }\n')
  assert.ok(pendingSyncCount(home, baseEnv(home)) > 0)
  sync(home)
  assert.equal(
    readFileSync(join(folderCopy(home, 'gemini'), 'lib/util.sh'), 'utf8'),
    'say_done() { echo "v2 $1"; }\n'
  )
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
})

test('REQ-HOOKS-SYNC-9 a folder copy edited in a tool is kept back into the library, or restored by an approved apply with a backup', () => {
  const home = folderScriptHome()
  sync(home)
  const util = join(folderCopy(home, 'claude'), 'lib/util.sh')
  writeFileSync(util, 'say_done() { echo "edited"; }\n')
  // The hooks using it show the edit
  const view = hooksView(home, baseEnv(home))
  assert.deepEqual(
    view.hooks.filter((h) => h.edited?.claude).map((h) => [h.name, h.edited!.claude]),
    [
      ['a', 'run.sh'],
      ['b', 'run.sh']
    ]
  )
  keepHookCopy(home, 'claude', 'a', 'run.sh')
  assert.equal(
    readFileSync(join(home, '.illithid/workspaces/default/scripts/fmt/lib/util.sh'), 'utf8'),
    'say_done() { echo "edited"; }\n'
  )
  sync(home)
  assert.equal(
    readFileSync(join(folderCopy(home, 'gemini'), 'lib/util.sh'), 'utf8'),
    'say_done() { echo "edited"; }\n'
  )
  // Edited again: automatic syncs leave it, an approved apply restores it after a backup
  writeFileSync(util, 'again\n')
  sync(home)
  assert.equal(readFileSync(util, 'utf8'), 'again\n')
  sync(home, true)
  assert.equal(readFileSync(util, 'utf8'), 'say_done() { echo "edited"; }\n')
  assert.equal(
    readFileSync(
      join(home, '.config/illithid/backups/hooks/claude/_scripts/fmt/lib/util.sh'),
      'utf8'
    ),
    'again\n'
  )
})

test('REQ-HOOKS-SYNC-10 a folder copy no hook in the tool uses any more is removed with a backup', () => {
  const home = folderScriptHome()
  sync(home)
  setToggle(home, 'hooks', 'a', 'claude', false)
  sync(home)
  // b still uses it
  assert.ok(existsSync(folderCopy(home, 'claude')))
  setToggle(home, 'hooks', 'b', 'claude', false)
  sync(home)
  assert.equal(existsSync(folderCopy(home, 'claude')), false)
  assert.ok(existsSync(folderCopy(home, 'gemini')))
  assert.ok(existsSync(join(home, '.config/illithid/backups/deleted')))
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
  // A tool-only script would lose the folder's other files
  assert.throws(() => createHookToolScript(home, 'a', 'gemini'), { code: 'invalidSchema' })
})
