import assert from 'node:assert/strict'
import { test } from 'node:test'
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { applyImport, planImport, readPermissions, syncAll } from '../src/engine'
import { baseEnv, buildDemoHome } from './readme-shots'

function demoHome(tools: string[]): string {
  const home = mkdtempSync(join(tmpdir(), 'illithid-perm-import-'))
  buildDemoHome(home, { tools: 'all' })
  const cfg = join(home, '.config/illithid/config.json')
  writeFileSync(
    cfg,
    JSON.stringify({ ...JSON.parse(readFileSync(cfg, 'utf8')), toolsInUse: tools })
  )
  return home
}

const variantOf = (home: string, source: string): Record<string, unknown> => {
  const plan = planImport(home, source)
  assert.equal(plan.permissions.length, 1, JSON.stringify(plan.notes))
  return plan.permissions[0].variants[0].allowlist as unknown as Record<string, unknown>
}

test('REQ-PERM-IMPORT-1 Claude Code permissions come in as command and MCP rules; other entries stay Claude-only', () => {
  const home = demoHome(['claude'])
  mkdirSync(join(home, '.claude'), { recursive: true })
  const settings = join(home, '.claude/settings.json')
  writeFileSync(
    settings,
    JSON.stringify({
      permissions: {
        allow: ['Bash(git status:*)', 'Bash(npm test)', 'WebFetch', 'mcp__context7'],
        deny: ['Bash(git push --force:*)', 'mcp__github__delete_repository', 'Read(./.env)'],
        ask: ['Bash(rm:*)', 'mcp__postgres__*']
      }
    })
  )
  assert.deepEqual(variantOf(home, 'tool:claude'), {
    bash: [['git', 'status'], { argv: ['npm', 'test'], claudeExact: true }],
    bashAsk: [['rm']],
    bashDeny: [['git', 'push', '--force']],
    mcp: [
      { decision: 'allow', server: 'context7', tool: '*' },
      { decision: 'ask', server: 'postgres', tool: '*' },
      { decision: 'deny', server: 'github', tool: 'delete_repository' }
    ],
    claudeOnly: { allow: ['WebFetch'], deny: ['Read(./.env)'] }
  })
  applyImport(home, [{ kind: 'permissions', name: 'permissions' }], 'tool:claude')
  assert.ok(readPermissions(home))
  syncAll(home, baseEnv(home), { allowReal: true, approvedOnce: true })
  const after = JSON.parse(readFileSync(settings, 'utf8')) as {
    permissions: Record<string, string[]>
  }
  // The same rules go back out (mcp__postgres__* is written as mcp__postgres: every tool of the server)
  assert.deepEqual(after.permissions.allow.sort(), [
    'Bash(git status:*)',
    'Bash(npm test)',
    'WebFetch',
    'mcp__context7'
  ])
  assert.deepEqual(after.permissions.deny.sort(), [
    'Bash(git push --force:*)',
    'Read(./.env)',
    'mcp__github__delete_repository'
  ])
  assert.deepEqual(after.permissions.ask.sort(), ['Bash(rm:*)', 'mcp__postgres'])
  // Nothing new to import afterwards
  assert.equal(planImport(home, 'tool:claude').permissions.length, 0)
})

test('REQ-PERM-IMPORT-2 Codex prompt and forbidden prefix rules come in as ask and block', () => {
  const home = demoHome(['codex'])
  mkdirSync(join(home, '.codex/rules'), { recursive: true })
  writeFileSync(
    join(home, '.codex/rules/default.rules'),
    [
      'prefix_rule(pattern=["ls"], decision="allow")',
      'prefix_rule(pattern=["rm"], decision="prompt")',
      'prefix_rule(pattern=["git", "push", "--force"], decision="forbidden")',
      ''
    ].join('\n')
  )
  const v = variantOf(home, 'tool:codex')
  assert.deepEqual(v.bash, [['ls']])
  assert.deepEqual(v.bashAsk, [['rm']])
  assert.deepEqual(v.bashDeny, [['git', 'push', '--force']])
})

test('REQ-PERM-IMPORT-3 Gemini CLI policy rules come in; the file Illithid writes is skipped', () => {
  const home = demoHome(['gemini'])
  mkdirSync(join(home, '.gemini/policies'), { recursive: true })
  writeFileSync(
    join(home, '.gemini/policies/mine.toml'),
    [
      '[[rule]]',
      'toolName = "run_shell_command"',
      'commandPrefix = "git push --force"',
      'decision = "deny"',
      'priority = 500',
      '',
      '[[rule]]',
      'toolName = "run_shell_command"',
      'commandPrefix = "npm"',
      'decision = "ask_user"',
      'priority = 100',
      '',
      '[[rule]]',
      'mcpName = "github"',
      'toolName = "delete_repository"',
      'decision = "deny"',
      'priority = 100',
      ''
    ].join('\n')
  )
  writeFileSync(
    join(home, '.gemini/policies/illithid.toml'),
    '# Generated by Illithid from the library permissions.json. Edit the rules in Illithid; this file is rewritten on sync.\n\n[[rule]]\ntoolName = "run_shell_command"\ncommandRegex = "^ls(\\\\s|$)"\ndecision = "allow"\npriority = 100\n'
  )
  const v = variantOf(home, 'tool:gemini')
  assert.deepEqual(v.bash, [])
  assert.deepEqual(v.bashAsk, [['npm']])
  assert.deepEqual(v.bashDeny, [['git', 'push', '--force']])
  assert.deepEqual(v.mcp, [{ decision: 'deny', server: 'github', tool: 'delete_repository' }])
})

test('REQ-PERM-IMPORT-4 Grok CLI [permission] rules come in as command and MCP rules', () => {
  const home = demoHome(['grok'])
  mkdirSync(join(home, '.grok'), { recursive: true })
  writeFileSync(
    join(home, '.grok/config.toml'),
    [
      '[permission]',
      'deny = ["Bash(rm -rf *)", "MCPTool(sales__delete_account)"]',
      'ask = ["Bash(git push:*)"]',
      'allow = ["Bash(git status)", "MCPTool(docs__*)", "Read(*)"]',
      ''
    ].join('\n')
  )
  const v = variantOf(home, 'tool:grok')
  assert.deepEqual(v.bash, [{ argv: ['git', 'status'], claudeExact: true }])
  assert.deepEqual(v.bashAsk, [['git', 'push']])
  assert.deepEqual(v.bashDeny, [['rm', '-rf']])
  assert.deepEqual(v.mcp, [
    { decision: 'allow', server: 'docs', tool: '*' },
    { decision: 'deny', server: 'sales', tool: 'delete_account' }
  ])
})
