import assert from 'node:assert/strict'
import { test } from 'node:test'
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  applyImport,
  createHook,
  hookTriggers,
  pendingSyncCount,
  planImport,
  readHook,
  saveHookDoc,
  savePermissionRules,
  syncAll,
  type PermissionRules
} from '../src/engine'
import { baseEnv, buildDemoHome } from './readme-shots'

/** Hooks are generated as POSIX shell scripts and not written on Windows yet (phase 1) */
const NO_HOOKS = process.platform === 'win32' && 'hooks are not written on Windows yet'

function qwenHome(): string {
  const home = mkdtempSync(join(tmpdir(), 'illithid-qwen-hooks-'))
  buildDemoHome(home)
  const cfg = join(home, '.config/illithid/config.json')
  writeFileSync(
    cfg,
    JSON.stringify({ ...JSON.parse(readFileSync(cfg, 'utf8')), toolsInUse: ['qwen'] })
  )
  return home
}
function writeSettings(home: string, value: unknown): string {
  const path = join(home, '.qwen/settings.json')
  mkdirSync(join(home, '.qwen'), { recursive: true })
  writeFileSync(path, JSON.stringify(value, null, 2) + '\n')
  return path
}
const sync = (home: string): void => {
  const r = syncAll(home, baseEnv(home), { allowReal: true, approvedOnce: true })
  assert.equal(r.refused, undefined)
  assert.deepEqual(r.plan.errors, [])
}
const json = (p: string): Record<string, unknown> => JSON.parse(readFileSync(p, 'utf8'))
const copyPath = (home: string, hook: string): string =>
  join(home, `.qwen/hooks/illithid/${hook}/run.sh`)

test(
  'a guard hook reaches Qwen Code next to its user hooks, matching run_shell_command',
  { skip: NO_HOOKS },
  () => {
    const home = qwenHome()
    const userHook = { matcher: 'edit', hooks: [{ type: 'command', command: '~/bin/mine.sh' }] }
    const path = writeSettings(home, { $version: 4, hooks: { PreToolUse: [userHook] } })
    createHook(home, 'guard', {
      description: '',
      when: 'before-tool',
      action: 'guard',
      options: {}
    })
    sync(home)
    const s = json(path) as { $version: number; hooks: { PreToolUse: unknown[] } }
    assert.equal(s.$version, 4)
    assert.deepEqual(s.hooks.PreToolUse, [
      userHook,
      {
        matcher: 'run_shell_command',
        hooks: [{ type: 'command', command: `'${copyPath(home, 'guard')}' qwen` }]
      }
    ])
    assert.match(
      readFileSync(copyPath(home, 'guard'), 'utf8'),
      /^#!\/bin\/sh\n# Generated by Illithid for qwen/
    )
    assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
  }
)

test(
  'Qwen hook timeouts are seconds; 1000 s or more is written in milliseconds, which Qwen reads as such',
  { skip: NO_HOOKS },
  () => {
    const home = qwenHome()
    const path = writeSettings(home, { $version: 4 })
    createHook(home, 'done', { description: '', when: 'stop', action: 'notify', options: {} })
    const doc = readHook(home, 'done').doc
    saveHookDoc(home, 'done', { ...doc, tools: { qwen: { timeout: 30 } } })
    sync(home)
    const hooks = (json(path) as { hooks: Record<string, { hooks: { timeout?: number }[] }[]> })
      .hooks
    assert.equal(hooks.Stop[0].hooks[0].timeout, 30)
    saveHookDoc(home, 'done', { ...doc, tools: { qwen: { timeout: 1200 } } })
    sync(home)
    const after = (json(path) as { hooks: Record<string, { hooks: { timeout?: number }[] }[]> })
      .hooks
    assert.equal(after.Stop[0].hooks[0].timeout, 1200000)
  }
)

const RULES: PermissionRules = {
  commands: [
    { decision: 'allow', argv: ['git', 'status'], exact: false },
    { decision: 'allow', argv: ['npm', 'test'], exact: true },
    { decision: 'ask', argv: ['rm'], exact: false },
    { decision: 'deny', argv: ['git', 'push', '--force'], exact: false }
  ]
}

test('Qwen Code gets allow, ask and deny rules in Claude syntax next to its own keys', () => {
  const home = qwenHome()
  const path = writeSettings(home, {
    $version: 4,
    model: { name: 'coder-model' },
    permissions: { autoMode: 'off' }
  })
  savePermissionRules(home, RULES)
  sync(home)
  const s = json(path) as { $version: number; model: unknown; permissions: unknown }
  assert.equal(s.$version, 4)
  assert.deepEqual(s.model, { name: 'coder-model' })
  assert.deepEqual(s.permissions, {
    autoMode: 'off',
    allow: ['Bash(git status:*)', 'Bash(npm test)'],
    deny: ['Bash(git push --force:*)'],
    ask: ['Bash(rm:*)']
  })
  assert.equal(pendingSyncCount(home, baseEnv(home)), 0)
})

test('without library permissions, Qwen permissions are left untouched', () => {
  const home = qwenHome()
  const permissions = { allow: ['Bash(ls:*)'], deny: ['Read(.env)'] }
  const path = writeSettings(home, { $version: 4, permissions })
  sync(home)
  assert.deepEqual(json(path).permissions, permissions)
})

test('Qwen hooks and permissions can be imported', () => {
  const home = qwenHome()
  mkdirSync(join(home, 'bin'), { recursive: true })
  writeFileSync(join(home, 'bin/guard.sh'), '#!/bin/sh\necho guard\n', { mode: 0o755 })
  writeSettings(home, {
    $version: 4,
    permissions: { allow: ['Bash(git status:*)'], deny: ['Bash(rm -rf:*)'] },
    hooks: {
      PreToolUse: [
        {
          matcher: 'run_shell_command',
          hooks: [{ type: 'command', command: '~/bin/guard.sh', timeout: 10 }]
        }
      ]
    }
  })
  const plan = planImport(home, 'tool:qwen')
  assert.equal(plan.permissions.length, 1)
  const guard = plan.hooks.find((c) => c.name === 'guard')
  assert.ok(guard, JSON.stringify(plan.hooks.map((c) => c.name)))
  assert.deepEqual(guard.variants[0].trigger, {
    event: 'PreToolUse',
    matcher: 'run_shell_command',
    timeout: 10
  })
  const results = applyImport(home, [{ kind: 'hook', name: 'guard' }], 'tool:qwen')
  assert.equal(results[0].status, 'imported', JSON.stringify(results))
  assert.deepEqual(hookTriggers(readHook(home, 'guard').doc).qwen, {
    event: 'PreToolUse',
    matcher: 'run_shell_command',
    timeout: 10
  })
})

test('Qwen also gets the non-Bash rules of the library (Claude syntax), and dropping a native rule is noted', () => {
  const home = qwenHome()
  const path = writeSettings(home, {
    $version: 4,
    permissions: { deny: ['Read(.env)', 'WebFetch(domain:evil.example)'] }
  })
  savePermissionRules(home, RULES)
  const lib = join(home, '.illithid/workspaces/default/permissions.json')
  writeFileSync(
    lib,
    JSON.stringify({ ...json(lib), claudeOnly: { allow: [], deny: ['Read(.env)'] } })
  )
  const r = syncAll(home, baseEnv(home), { allowReal: true, approvedOnce: true })
  assert.deepEqual(r.plan.errors, [])
  const change = r.plan.targets.find((c) => c.id === 'qwenPermissions')
  assert.ok(
    change?.notes.some((n) => n.includes('WebFetch(domain:evil.example)')),
    JSON.stringify(change?.notes)
  )
  const s = json(path) as { permissions: { deny: string[] } }
  assert.deepEqual(s.permissions.deny, ['Bash(git push --force:*)', 'Read(.env)'])
})
